{
    'name': "Property Management",
    'version': '1.0',
    'summary': 'This module provides a complete property rental management system for real estate businesses and property managers. It enables users to manage properties, register tenants, create and track lease agreements, and automate rent calculations and payments. ',
    'depends': ['base', 'mail','web', 'crm','sale_management','product'],
    'author': 'Tirufat Tesfaye',
    'sequence': 0,
    'category': 'Real Estate',
    'data': [
        'security/ir.model.access.csv',
        'security/property_management_security.xml',
        'views/property_views.xml',
        'views/tenant_views.xml',
        'views/leases_views.xml',
        'views/rent_payment_views.xml',
        'views/menu.xml',
        'views/property_crm_views.xml',
        'views/property_sale_views.xml',
        'report/lease_summary_template.xml',
        'wizard/lease_summary_wizard_view.xml',
        'wizard/rent_payment_excel_wizard.xml',
        'data/tenant_id.xml',
        'data/payment_name.xml',
        'data/cron.xml',
        'data/email.xml',
    ],
    'installable': True,
    'application': True,
}
